import React from 'react';
import { Sparkles, Shield, AlertCircle, Database, Activity, Brain, Lock, Eye } from 'lucide-react';

export default function EvidenceSummary({ summary, evidence }) {
  const stolen = evidence?.stolenDataTypes || [];
  const behaviors = evidence?.suspiciousBehaviors || [];

  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Main Container with clean white background */}
     <div className="relative bg-white rounded-2xl p-8 shadow-lg border border-gray-200 overflow-hidden">

        
        {/* Subtle corner gradients */}
<div className="pointer-events-none absolute -top-20 -left-20 w-64 h-64 bg-[#4db5c4]/20 rounded-full blur-3xl" />
<div className="pointer-events-none absolute -bottom-20 -right-20 w-64 h-64 bg-[#006b7d]/20 rounded-full blur-3xl" />

        <div className="relative z-10 space-y-6">
          
          {/* Header with AI badge */}
          <div className="flex items-center justify-between mb-4 pb-4  border-gray-200">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-[#006b7d] rounded-lg shadow-md">
                <Brain className="w-6 h-6 text-white" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-gray-900">AI Analysis Report</h2>
                <p className="text-sm text-gray-600">Generated by neural threat detection</p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-1.5 bg-[#e8f6f9] rounded-full border border-[#4db5c4]">
              <Sparkles className="w-4 h-4 text-[#006b7d]" />
              <span className="text-xs font-medium text-[#006b7d]">AI Powered</span>
            </div>
          </div>

          {/* Two Column Layout */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            
            {/* Left Column: Data Detection */}
            <div className="bg-transparent rounded-xl p-6 border border-gray-200 shadow-sm h-full flex flex-col">
             
              {stolen.length > 0 && (
                <div className="">
                  <div className="flex items-center gap-2 mb-4">
                    <div className="p-2 bg-red-500 rounded-lg shadow-sm">
                      <Lock className="w-5 h-5 text-white" />
                    </div>
                    <div>
                      <h4 className="text-lg font-semibold text-gray-900">
                        Compromised Data Detection
                      </h4>
                      <p className="text-xs text-gray-600">Sensitive information being harvested</p>
                    </div>
                  </div>

                  <div className="">
                    <div className="flex flex-wrap gap-2">
                      {stolen.map((item, i) => (
                        <div
                          key={i}
                          className="group relative px-4 py-2 bg-red-50 border border-red-200 rounded-lg hover:bg-red-100 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md"
                        >
                          <div className="flex items-center gap-2">
                            <Database className="w-4 h-4 text-red-600" />
                            <span className="text-sm font-medium text-red-900">{item}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Right Column: Suspicious Behaviors */}
            {behaviors.length > 0 && (
              <div className="bg-transparent rounded-xl p-6 shadow-sm border border-gray-200 h-full">
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-2 bg-[#1a8a9a] rounded-lg shadow-sm">
                    <Eye className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold text-gray-900">
                      Anomalous Behavior Patterns
                    </h4>
                    <p className="text-xs text-gray-600">AI-detected suspicious activities</p>
                  </div>
                </div>

                <div className="">
                  <div className="space-y-3">
                    {behaviors.map((behavior, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg border border-gray-200 hover:border-gray-300 hover:bg-gray-100 transition-colors group"
                      >
                        <div className="mt-0.5 p-1.5 bg-[#e8f6f9] rounded-md group-hover:bg-[#cdedf3] transition-colors">
                          <AlertCircle className="w-4 h-4 text-[#006b7d]" />
                        </div>
                        <p className="text-[15px] text-gray-700 leading-relaxed flex-1">{behavior}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* AI Confidence Footer */}
          <div className="flex items-center justify-between pt-4 border-t border-gray-200">
            <div className="flex items-center gap-2 text-sm text-gray-600">
              <Shield className="w-4 h-4 text-[#006b7d]" />
              <span>Analysis confidence: <strong className="text-gray-900">99.2%</strong></span>
            </div>
            <div className="text-xs text-gray-500">
              Last updated: {new Date().toLocaleTimeString()}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Demo component with dummy data
export function EvidenceSummaryDemo() {
  const dummyData = {
    summary: "Our advanced AI neural network has identified this website as a sophisticated credential harvesting operation. The analysis reveals multiple layers of deceptive practices including fake login portals, misleading security badges, and unauthorized data collection mechanisms. The threat actor is using social engineering techniques combined with visual mimicry of legitimate services to lower user vigilance.",
    evidence: {
      stolenDataTypes: [
        "Email Addresses",
        "Passwords",
        "Credit Card Numbers",
        "Social Security Numbers",
        "Phone Numbers",
        "Billing Addresses",
        "Bank Account Details",
        "Security Questions"
      ],
      suspiciousBehaviors: [
        "Website attempts to mimic the visual design and branding of a well-known financial institution without authorization",
        "SSL certificate does not match the claimed organization, indicating potential man-in-the-middle attack setup",
        "Form submissions are redirected to an unrelated third-party domain registered in a high-risk jurisdiction",
        "JavaScript code contains obfuscated functions that attempt to capture keystrokes and clipboard data",
        "Site displays fake security badges and trust seals from organizations that have not verified or endorsed this website",
        "Multiple hidden iframes detected that load content from known malicious domains",
        "Browser fingerprinting scripts identified that collect device information beyond normal analytics",
        "Urgency-creating language and countdown timers designed to pressure users into hasty decisions"
      ]
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <EvidenceSummary 
        summary={dummyData.summary} 
        evidence={dummyData.evidence} 
      />
    </div>
  );
}